name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - staging
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  run_tests:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
            python-version: '3.x'
       - name: Install dependencies
         run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
       - name: Checkout Repository
         uses: actions/checkout@v2
       - name: Run Tests
         run: |
          pip install pytest pytest-cov
          pytest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Flask Application
        if: ${{ needs.run_tests.outputs.TESTS_FAILED != 'true' }}
        run: |
        

  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
            - name: Checking out code on Runner
              uses: actions/checkout@v4

            - name: login and update the EC2 instance
              uses: appleboy/ssh-action@v1.0.3    #The main difference between SSH and SCP is that SSH is used for logging into remote systems and for controlling those systems while SCP is used for transferring files among remote computers in a network
              with:
                   host: ${{ secrets.EC2_HOST }}
                   username: ${{ secrets.EC2_USERNAME }}
                   key: ${{ secrets.EC2_SSH_KEY }}
                   port: 22
                   script: |
                        whoami
                        sudo apt-get update -y
                        sudo apt-get install nginx -y
                        sudo mkdir -p /var/www/html
                        sudo chown -R ${{secrets.EC2_USERNAME}} /var/www/html
                        sudo chmod -R 755 /var/www/html
            -  name: copy file via ssh password
               uses: appleboy/scp-action@v0.1.7  #The main difference between SSH and SCP is that SSH is used for logging into remote systems and for controlling those systems while SCP is used for transferring files among remote computers in a network
               with:
                   host: ${{ secrets.EC2_HOST }}
                   username: ${{ secrets.EC2_USERNAME }}
                   key: ${{ secrets.EC2_SSH_KEY }}
                   port: 22
                   source: ./
                   target: /var/www/html

            - name: restart nginx
              uses: appleboy/ssh-action@v1.0.3
              with:
                   host: ${{ secrets.EC2_HOST }}
                   username: ${{ secrets.EC2_USERNAME }}
                   key: ${{ secrets.EC2_SSH_KEY }}
                   port: 22
                   script: |
                       sudo systemctl restart nginx
